name: jekul 
on:
push:
 branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

workflow_dispatch:
 
      job:
     build:
          run on: ubuntu-latest 

       steps:
           
           - name: Check out
             uses: action/checkout@v3
   
           - name: Dotnet-script 
              run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json
